id: opecha:P001754
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1016782
  title: མངོན་རྟོགས་རྒྱན་རྩ་འགྲེལ་རྣམས་གསལ་བར་བྱེད་པ་བློ་བཟང་དགོངས་རྒྱན་གདོང་ལྔའི་དབང་པོའི་སྒྲ་དབྱངས
  volume: ''
  author: ''
